apps/management_employee/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("timeclockindex/", views.index, name="timeclockindex"),
    path("home/", views.home, name="home"),
    path("register/", views.register, name="register"),
    path("logout/", views.logout, name="logout"),
    path("schedule/", views.schedule, name="schedule"),
    path("stopschedule/", views.stopschedule, name="stopschedule"),
]

management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.management_employee.urls")),
]

apps/management_employee/models.py
from django.db import models
from django.utils import timezone
from datetime import date


class Emp(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    recovery_answer = models.CharField(max_length=20)
    recovery_email = models.CharField(max_length=50)
    created_on = models.DateTimeField(default=timezone.now)
    last_updated_on = models.DateTimeField(blank=True, null=True)
    deleted_on = models.DateTimeField(blank=True, null=True)
    first_name = models.CharField(max_length=40)
    middle_name = models.CharField(max_length=40, blank=True, default="")
    last_name = models.CharField(max_length=40)
    phone_number = models.IntegerField(blank=True, null=True)
    created_on = models.DateTimeField(default=timezone.now)
    deleted_on = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.username


class Employee(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    recovery_answer = models.CharField(max_length=20)
    recovery_email = models.CharField(max_length=20)
    created_on = models.DateTimeField(default=timezone.now)
    last_updated_on = models.DateTimeField(blank=True, null=True)
    deleted_on = models.DateTimeField(blank=True, null=True)

    # class Meta:
    #     verbose_name_plural = "Funcionlario"

    def __str__(self):
        return "ID: %d Username: %s Password: %s" % (
            self.id,
            self.username,
            self.password,
        )


class EmployeeInfo(models.Model):
    employee = models.ForeignKey("Employee", on_delete=models.CASCADE)
    first_name = models.CharField(max_length=40)
    middle_name = models.CharField(max_length=40, blank=True, default="")
    last_name = models.CharField(max_length=40)
    department = models.CharField(max_length=50, default="")
    phone_number = models.IntegerField(blank=True, null=True)
    created_on = models.DateTimeField(default=timezone.now)
    deleted_on = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return (
            "ID: %d First Name: %s Middle Name: %s Last Name: %s Phone Number: %s"
            % (
                self.id,
                self.first_name,
                self.middle_name,
                self.last_name,
                self.phone_number,
            )
        )


class Status(models.Model):
    types = models.CharField(max_length=30)

    def __str__(self):
        return "%d %s" % (self.id, self.types)


class Work(models.Model):
    employee = models.ForeignKey("Employee", on_delete=models.CASCADE)
    work_status = models.CharField(max_length=30)
    notes = models.CharField(max_length=100, default="", blank=True)
    time = models.TimeField(default=timezone.localtime)
    date = models.DateField(default=date.today)

    def __str__(self):
        return "ID: %d Work Status: %s Notes: %s Time: %s Date: %s" % (
            self.id,
            self.work_status,
            self.notes,
            self.time,
            self.date,
        )


class User(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)

    def __str__(self):
        return "username: {}, password: {}".format(self.username, self.password)

apps/management_employee/forms.py
from django import forms


class LoginForms(forms.Form):
    username = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Usuário"}
        ),
    )
    password = forms.CharField(
        max_length=30,
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Senha"}
        ),
    )


class LogStatus(forms.Form):
    notes = forms.CharField(
        max_length=50,
        widget=forms.Textarea(attrs={"class": "form-control", "placeholder": "Notes"}),
    )


class RegisterForms(forms.Form):
    username = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Usuário"}
        ),
    )
    password = forms.CharField(
        max_length=30,
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Senha"}
        ),
    )
    # recovery_answer = forms.CharField(max_length=30,
    #                                   widget=forms.TextInput(
    #                                       attrs={'class': 'form-control', 'placeholder': 'Recovery Answer'}))
    recovery_email = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "E-mail de Recuperação"}
        ),
    )
    first_name = forms.CharField(
        max_length=50,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Primeiro Nome"}
        ),
    )
    middle_name = forms.CharField(
        max_length=50,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Nome do Meio"}
        ),
    )
    last_name = forms.CharField(
        max_length=50,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Sobrenome"}
        ),
    )
    department = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Departamento"}
        ),
    )
    phone_number = forms.IntegerField(
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Número de telefone"}
        )
    )

apps/management_employee/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . import forms
from .models import Employee, EmployeeInfo, Status, Work
from . import mailer
import datetime

userExistsStatus = False
userRef = ""


def schedule(request):
    mailer.scheduleMailJob()
    return redirect("index")


def stopschedule(request):
    mailer.stopMailer()
    return redirect("index")


def logout(request):
    global userExistsStatus, userRef
    userExistsStatus = False
    userRef = ""
    try:
        del request.session["user_id"]
    except KeyError:
        pass
    return redirect("index")


def delSession(request):
    global userExistsStatus, userRef
    userExistsStatus = False
    userRef = ""
    try:
        del request.session["user_id"]
    except KeyError:
        pass
    return HttpResponse("Session terminated...")


def login(request):
    try:
        user = Employee.objects.get(username=request.POST["username"])
        if user.password == request.POST["password"]:
            request.session["user_id"] = user.id
            global userExistsStatus, userRef
            userExistsStatus = True
            userRef = request.POST["username"]
            return True
        else:
            delSession(request)
            return False
    except Employee.DoesNotExist:
        delSession(request)
        return False


def index(request):
    if request.method == "POST":
        loginForm = forms.LoginForms()
        if loginForm.is_valid:
            if login(request):
                return redirect("home")
            context = {
                "form": loginForm,
                "message": "Nome de usuário e senha não correspondem!!!",
            }
            return render(request, "emptimeclklogmgmt/index.html", context)
    else:
        delSession(request)
        loginForm = forms.LoginForms()
        context = {"form": loginForm}
        return render(request, "emptimeclklogmgmt/index.html", context)


def home(request):
    if userExistsStatus:
        # logstatusForm = forms.LogStatus()
        if request.method == "POST":
            # retrieving the employee from Employee
            employee = Employee.objects.get(username=str(userRef))

            # create a new entry of time log status for the employee
            employee.work_set.create(
                work_status=request.POST["status_drop"],
                # notes=request.POST['notes']
            )

            employees = Employee.objects.all()
            return redirect("home")
        else:
            employees = Employee.objects.all()
            statuses = Status.objects.all()
            work_statuses = Work.objects.filter(date=datetime.date.today())
            ws_desc = work_statuses.order_by("-time")
            # context = {'ws_desc': ws_desc, 'employees': employees, 'statuses': statuses, 'logstatus': logstatusForm, 'userRef': userRef}
            context = {
                "ws_desc": ws_desc,
                "employees": employees,
                "statuses": statuses,
                "userRef": userRef,
            }
            return render(request, "emptimeclklogmgmt/homepage.html", context)
    else:
        return HttpResponse(
            "Falha no sistema, faça novamente o Login usando o link: 'http://127.0.0.1:8000/' "
        )


def register(request):
    registerForm = forms.RegisterForms()
    if request.method == "POST":
        if registerForm.is_valid:
            empObj = Employee(
                username=request.POST["username"],
                password=request.POST["password"],
                # recovery_answer=request.POST['recovery_answer'],
                recovery_email=request.POST["recovery_email"],
            )
            empObj.save()
            empInfoObj = EmployeeInfo(
                employee=empObj,
                first_name=request.POST["first_name"],
                middle_name=request.POST["middle_name"],
                department=request.POST["department"],
                last_name=request.POST["last_name"],
                phone_number=request.POST["phone_number"],
            )
            empInfoObj.save()
        return redirect("index")
    else:
        context = {"user": registerForm}
        return render(request, "emptimeclklogmgmt/registeruser.html", context)

apps/management_employee/templates/emptimeclklogmgmt/homepage.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="">
        <meta name="author" content="">
    
        <title>Employee Time Clock v1.0</title>
    
        <!-- Bootstrap core CSS -->
        <link href="{% static 'emptimeclklogmgmt/bootstrap.min.css' %}" rel="stylesheet"> 
        <!-- Bootstrap theme -->
        <link href="{% static 'emptimeclklogmgmt/bootstrap-theme.min.css' %}" rel="stylesheet">
    
        <!-- Custom styles for this template -->
        <link href="{% static 'emptimeclklogmgmt/sign.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="container theme-showcase">
            <div>
                <h1><center>Gestão de ponto - Academia Movimento</center> </h1>
                <table class="table">
                    <tbody>
                        <tr>
                            <td class="text-left">
                                Usuário On-line - {{userRef}}
                            </td>
                            <td class="text-right">
                            <a href="{% url 'logout' %}" class="btn btn-md btn-primary">Sair</a>
                        </td></tr>
                    </tbody>
                </table>
            </div>
            <br><br>
            <div class="row"> 
                    <div class="table-responsive col-md-2">
                        <form method="POST" action="{% url 'home' %}">
                            {% csrf_token %}
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td>Entrada/Saída:
                                            <br>
                                            <div>                                                
                                                <select name='status_drop'>
                                                    <option selected></option>
                                                    {% for status in statuses %}
                                                    <option>{{status.types}}</option>
                                                    {% endfor %}
                                                </select>
                                            </div>
                                        </td>
                                    </tr>
<!--                                    <tr>-->
<!--                                        <td>Observações:-->
<!--                                            <br>-->
<!--                                            {{logstatus.notes}}-->
<!--                                        </td>-->
<!--                                    </tr>-->
                                    <tr>
                                        <td> <br>
                                            <button class="btn btn-sm btn-primary">Registrar</button>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </form>
                    </div>
                <div class="table-responsive col-md-10">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Nome</th>
                                <th>Entrada/Saída</th>
                                <th>Horário</th>
                                <th>Data</th>
                                <th>Departamento/Função</th>
<!--                                <th>Observações</th>-->
                            </tr>
                        </thead>
                        {% for ws in ws_desc %}
                        <tbody>
                            <tr>
                                <td>
                                    {{ws.employee.employeeinfo_set.all.0.first_name}} {{ws.employee.employeeinfo_set.all.0.last_name}}
                                </td>
                                <td>
                                    {{ws.work_status}}
                                </td>
                                <td>
                                    {{ws.time}}
                                </td>
                                <td>
                                    {{ws.date}}
                                </td>
                                <td>
                                    {{ws.employee.employeeinfo_set.all.0.department}}
                                </td>
<!--                                <td>-->
<!--                                    {{ws.notes}}-->
<!--                                </td>-->
                            </tr>
                        </tbody>    
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </body>
</html>

apps/management_employee/templates/emptimeclklogmgmt/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="">
        <meta name="author" content="">
    
        <title>Employee Time Clock v1.0</title>
    
        <!-- Bootstrap core CSS -->
        <link href="{% static 'emptimeclklogmgmt/bootstrap.min.css' %}" rel="stylesheet"> 
        <!-- Bootstrap theme -->
        <link href="{% static 'emptimeclklogmgmt/bootstrap-theme.min.css' %}" rel="stylesheet">
    
        <!-- Custom styles for this template -->
        <link href="{% static 'emptimeclklogmgmt/sign.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="container theme-showcase" role="main">
            <div class="jumbotron">
                <h1><center>Faça seu Login</center> </h1>
            </div>
        </div>

        <div class="container">
            <form class="form-signin" method="POST" action="{% url 'index' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="inputName" class="sr-only">Username</label>
                    {{form.username}}
                </div>
                <div class="form-group">
                    <label for="inputPassword" class="sr-only">Password</label>
                    {{form.password}}
                </div>
                <div>
                    {{message}}
                </div>
                <br>
                <center>
                    <button class="btn btn-lg btn-primary" type="submit">Log In</button>
                    <a href="{% url 'register' %}" class="btn btn-lg btn-primary">Registrar-se</a>
                    <!--
                    <a href="{% url 'schedule' %}" class="btn btn-lg btn-primary">Check Scheduled Mail</a>
                    <a href="{% url 'stopschedule' %}" class="btn btn-lg btn-primary">Stop Schedule</a>
                    -->
                </center>
            </form>
        </div>
    </body>
</html>

apps/management_employee/templates/emptimeclklogmgmt/registeruser.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="">
        <meta name="author" content="">
    
        <title>Employee Time Clock v1.0</title>
    
        <!-- Bootstrap core CSS -->
        <link href="{% static 'emptimeclklogmgmt/bootstrap.min.css' %}" rel="stylesheet"> 
        <!-- Bootstrap theme -->
        <link href="{% static 'emptimeclklogmgmt/bootstrap-theme.min.css' %}" rel="stylesheet">
    
        <!-- Custom styles for this template -->
        <link href="{% static 'emptimeclklogmgmt/sign.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="container theme-showcase" role="main">
            <div class="jumbotron">
                <h1><center>Registrando novo usuário</center> </h1>
            </div>
        </div>

        <div class="container">
            <form class="form-signin" method="POST" action="{% url 'register' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="inputName" class="sr-only">Usuário</label>
                    {{user.username}}
                </div>
                <div class="form-group">
                    <label for="inputPassword" class="sr-only">Password</label>
                    {{user.password}}
                </div>
<!--                <div class="form-group">-->
<!--                    <label for="inputRecoveryAnswer" class="sr-only">Recovery Answer</label>-->
<!--                    {{user.recovery_answer}}-->
<!--                </div>-->
                <div class="form-group">
                    <label for="inputRecoveryEmail" class="sr-only">E-mail de Recuperação</label>
                    {{user.recovery_email}}
                </div>
                <div class="form-group">
                    <label for="inputFirstName" class="sr-only">Primeiro Nome</label>
                    {{user.first_name}}
                </div>
                <div class="form-group">
                    <label for="inputMiddleName" class="sr-only">Nome do Meio</label>
                    {{user.middle_name}}
                </div>
                <div class="form-group">
                    <label for="inputLastName" class="sr-only">Sobrenome</label>
                    {{user.last_name}}
                </div>
                <div class="form-group">
                    <label for="inputDepartment" class="sr-only">Departamento</label>
                    {{user.department}}
                </div>
                <div class="form-group">
                    <label for="inputPhoneNumber" class="sr-only">Número de telefone</label>
                    {{user.phone_number}}
                </div>
                <center>
                    <button class="btn btn-lg btn-primary" type="submit">Registrar Usuário</button>
                    <a href="{% url 'timeclockindex' %}" class="btn btn-lg btn-primary">Voltar</a>
                </center>
            </form>
        </div>
    </body>
</html>